// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.
// <auto-generated />
// No style analysis for imported project.

using System;
using CodeHighlighter;

namespace Highlighter
{
    /// <summary>
    /// Provides easy access to ColorCode's built-in formatters.
    /// </summary>
    internal static class Formatters
    {
        /// <summary>
        /// Gets the default formatter.
        /// </summary>
        /// <remarks>
        /// The default formatter produces HTML with inline styles.
        /// </remarks>
        public static IFormatter Default { get { 
        //    return /*new HtmlFormatter()*/ null; 
            throw new InvalidOperationException();
        } }
    }
}