// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.
// <auto-generated />
// No style analysis for imported project.

namespace CodeHighlighter.Common
{
    internal static class LanguageId
    {
        public const string Css = "css";
        public const string Php = "php";
        public const string AspxVb = "aspx(vb.net)";
        public const string AspxCs = "aspx(c#)";
        public const string Xml = "xml";
        public const string Ashx = "ashx";
        public const string Aspx = "aspx";
        public const string Asax = "asax";
        public const string CSharp = "c#";
        public const string Html = "html";
        public const string JavaScript = "javascript";
        public const string Sql = "sql";
        public const string VbDotNet = "vb.net";
        public const string Cpp = "cpp";
    }
}